<?php

namespace Wefabric\Address\Providers;

class ServiceProvider extends \Illuminate\Support\ServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->publishes([
            __DIR__.'/../../database/migrations/' => database_path('migrations')
        ], ['wefabric_address', 'migrations']);

        $this->publishes([
            __DIR__.'/../../config/address.php' => config_path('address.php'),
        ], ['wefabric_address', 'config']);

        $this->loadTranslationsFrom(__DIR__.'/../../resources/lang', 'wefabric_address');
    }
}
